In [2]:
import pandas as pd
import requests
from collections import defaultdict
import time

input_df = pd.read_csv('addresses.csv', index_col=0)
input_df.head()

                                            0
0          3DKcHmHdqcUDAX2Yi2sjX9Hauam25Nk5Ja
1          3JNZyt1ocETf9oHscQfx17XNqY3odHAjaR
2  bc1q0xur68lq587lw8aqf96f4qqcmum6sqcpyyy94a
3          3JjtnDXknvY7HWidn5wt5BdZsRdXCGEt8y
4          3J9rQSzvNThPdN5FDbJAD3N8Wdce1KF6Ms

In [3]:
btc_hashes = input_df['0'].values
addr_data = defaultdict(list)
i = 0
for btc_hash in btc_hashes[:100]: # limiting for testing
    last_tx = ''
    while(True):
        URL = "https://blockstream.info/api/address/{}/txs/chain"
        if last_tx != '':
            URL+=f'/{last_tx}'

        data = requests.get(URL.format(btc_hash))


        data = data.json()
        addr_data[btc_hash].extend(data)
        if (len(data) < 25):
            break
        last_tx = data[-1]['txid']
    i+=1
    if i % 20 == 0:
        print(f"{i}/{len(btc_hashes)}")
    # time.sleep(1)
print(f"{i}/{len(btc_hashes)}")

20/899
40/899
60/899
80/899
100/899
100/899

In [43]:
history = pd.DataFrame()

for addr in addr_data.keys():
    for tx in addr_data[addr]:
        amount = 0
        for v_in in tx['vin']:
            if v_in['prevout']['scriptpubkey_address'] == addr:
                amount += v_in['prevout']['value']
        amount = -amount

        for v_out in tx['vout']:
            if v_out['scriptpubkey_address'] == addr:
                amount += v_out['value'] 
                
#         amount /= 1e8
        
        tx_history = {
            'time': tx['status']['block_time'],
            'addr': addr,
            'value': amount,
            'txid':tx['txid']
        }
        tx_df = pd.DataFrame(tx_history, index=[0])
        history = history.append(tx_df, ignore_index=True)
#     break

history

,time,addr,value,txid
0,1589052010,3DKcHmHdqcUDAX2Yi2sjX9Hauam25Nk5Ja,-1310546000,c5fc5cd22c553207714ac3fa6f51645d47be707b6d5122...
1,1589050796,3DKcHmHdqcUDAX2Yi2sjX9Hauam25Nk5Ja,1310546000,4a72fc833a5ab16ad45627a3aa499f4b1ab44363a88dda...
2,1581792148,3DKcHmHdqcUDAX2Yi2sjX9Hauam25Nk5Ja,-5000000000,f9aaddbc3a7fd1079e4418dc2b0a8be76caa42c4127819...
3,1581789478,3DKcHmHdqcUDAX2Yi2sjX9Hauam25Nk5Ja,5000000000,0206a1c8723c7a0ef894354da3a4cdfa9787541c759a18...
4,1589052010,3JNZyt1ocETf9oHscQfx17XNqY3odHAjaR,-1310507782,c5fc5cd22c553207714ac3fa6f51645d47be707b6d5122...
...,...,...,...,...
224,1618857406,14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5,-2285754,9f34c4b728977ff12910d88aff65735c1dabb70288d520...
225,1618511960,14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5,2285754,0ab3664e58993cb6282158d50a5a463d34515e41f91f51...
226,1597281548,14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5,-20033489,4acfce48e2cfeb03b5c309ba6d2669f30fdb54b147c002...
227,1597160347,14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5,9993333,10428738c09276668c483fded58288dc1ee5b0da833746...
228,1597076407,14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5,10040156,114fae6405a584b61c173ef125517a1ca1f7880486d032...

In [44]:
history = history.sort_index()
history['balance']  =  history.value.cumsum().div(1e8)

In [45]:
history

,time,addr,value,txid,balance
0,1589052010,3DKcHmHdqcUDAX2Yi2sjX9Hauam25Nk5Ja,-1310546000,c5fc5cd22c553207714ac3fa6f51645d47be707b6d5122...,-13.105460
1,1589050796,3DKcHmHdqcUDAX2Yi2sjX9Hauam25Nk5Ja,1310546000,4a72fc833a5ab16ad45627a3aa499f4b1ab44363a88dda...,0.000000
2,1581792148,3DKcHmHdqcUDAX2Yi2sjX9Hauam25Nk5Ja,-5000000000,f9aaddbc3a7fd1079e4418dc2b0a8be76caa42c4127819...,-50.000000
3,1581789478,3DKcHmHdqcUDAX2Yi2sjX9Hauam25Nk5Ja,5000000000,0206a1c8723c7a0ef894354da3a4cdfa9787541c759a18...,0.000000
4,1589052010,3JNZyt1ocETf9oHscQfx17XNqY3odHAjaR,-1310507782,c5fc5cd22c553207714ac3fa6f51645d47be707b6d5122...,-13.105078
...,...,...,...,...,...
224,1618857406,14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5,-2285754,9f34c4b728977ff12910d88aff65735c1dabb70288d520...,49.650354
225,1618511960,14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5,2285754,0ab3664e58993cb6282158d50a5a463d34515e41f91f51...,49.673211
226,1597281548,14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5,-20033489,4acfce48e2cfeb03b5c309ba6d2669f30fdb54b147c002...,49.472876
227,1597160347,14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5,9993333,10428738c09276668c483fded58288dc1ee5b0da833746...,49.572810
228,1597076407,14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5,10040156,114fae6405a584b61c173ef125517a1ca1f7880486d032...,49.673211

In [49]:
wallet_txs = pd.DataFrame()
progress = 0

for addr in addr_data.keys(): # here the addr_data is same that was calculated before
    for tx in addr_data[addr]:
        for vin in tx['vin']:
            tx_in = {}

            tx_in['timestamp'] = tx['status']['block_time']
            tx_in['tx_hash']   = tx['txid']
            tx_in['amount']    = vin['prevout']['value']
            tx_in['tx_type']   = 'deposit'
            tx_in['type']      = 'btc'
            tx_in['address']   = vin['prevout']['scriptpubkey_address']
            wallet_txs = wallet_txs.append(pd.DataFrame(tx_in,index=[0]))


    progress+=1
    if (progress % 10 == 0):
        print(f"progress {progress}/{len(addr_data)} txs")        
print(f"progress {progress}/{len(addr_data)} txs")        
    

wallet_txs = wallet_txs.set_index('address')
wallet_txs['address'] = wallet_txs.index

wallet_txs

progress 10/100 txs
progress 20/100 txs
progress 30/100 txs
progress 40/100 txs
progress 50/100 txs
progress 60/100 txs
progress 70/100 txs
progress 80/100 txs
progress 90/100 txs
progress 100/100 txs

,timestamp,tx_hash,amount,tx_type,type,address
address,,,,,,
3DKcHmHdqcUDAX2Yi2sjX9Hauam25Nk5Ja,1589052010,c5fc5cd22c553207714ac3fa6f51645d47be707b6d5122...,1310546000,deposit,btc,3DKcHmHdqcUDAX2Yi2sjX9Hauam25Nk5Ja
3DzNH41tkWt3YYbwkWYLUi8fD7Rj6WJrnX,1589052010,c5fc5cd22c553207714ac3fa6f51645d47be707b6d5122...,51927,deposit,btc,3DzNH41tkWt3YYbwkWYLUi8fD7Rj6WJrnX
3EWxsS8SBYKmYn3aPQ2uu84iehK8J5MGNW,1589052010,c5fc5cd22c553207714ac3fa6f51645d47be707b6d5122...,100000,deposit,btc,3EWxsS8SBYKmYn3aPQ2uu84iehK8J5MGNW
3HbWgReV2hgvrR6g7VhiWxcz6QY8aYwviK,1589052010,c5fc5cd22c553207714ac3fa6f51645d47be707b6d5122...,749859,deposit,btc,3HbWgReV2hgvrR6g7VhiWxcz6QY8aYwviK
3JNZyt1ocETf9oHscQfx17XNqY3odHAjaR,1589052010,c5fc5cd22c553207714ac3fa6f51645d47be707b6d5122...,1310507782,deposit,btc,3JNZyt1ocETf9oHscQfx17XNqY3odHAjaR
...,...,...,...,...,...,...
14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5,1597281548,4acfce48e2cfeb03b5c309ba6d2669f30fdb54b147c002...,10040156,deposit,btc,14q8cG1Mt5bUN1jytLvUzo9PpuTfCwBqK5
17vU2cT6fMpzmxU6irdEk6HotC9Pb1EYDG,1597281548,4acfce48e2cfeb03b5c309ba6d2669f30fdb54b147c002...,1500000000,deposit,btc,17vU2cT6fMpzmxU6irdEk6HotC9Pb1EYDG
1BZbjL9zooXs3VFgva9oMQaVeQecsMK8PC,1597281548,4acfce48e2cfeb03b5c309ba6d2669f30fdb54b147c002...,500000000,deposit,btc,1BZbjL9zooXs3VFgva9oMQaVeQecsMK8PC
3JkgZZd5sozLDnJMEPTjFAV1osdNfv88iZ,1597160347,10428738c09276668c483fded58288dc1ee5b0da833746...,298455000,deposit,btc,3JkgZZd5sozLDnJMEPTjFAV1osdNfv88iZ
bc1qr3wejdsenx5c72xlk0nsglr33xh4kmuzpefpnc,1597076407,114fae6405a584b61c173ef125517a1ca1f7880486d032...,1000000000,deposit,btc,bc1qr3wejdsenx5c72xlk0nsglr33xh4kmuzpefpnc